### ISSUE TITLE
Is there any way to add a NSNumberFormatter?

### ISSUE THREAD

**Issue by CharlesW95** [tbaranes/IncrementableLabel#6]
For example, if I would like to display the numbers with commas in between every thousand: 1,000,000, which we can achieve with NSNumberFormatter.

Thanks!

**Comment by tbaranes** [comment]
You can do this using the property `stringFormatter` which is a closure returning the string formatted, for example:

``` swift
anIncrementableLabel.stringFormatter = { value in
    let formatter = NumberFormatter()
    formatter.usesGroupingSeparator = true
    formatter.groupingSeparator = ","
    formatter.groupingSize = 3
    return formatter.stringFromNumber(NSNumber(float: value)) ?? ""
}
```

Also, that will work if you are working with plain string, but you also have `attributedTextFormatter` which is working the same way but for `NSAttributedString`

**Comment by CharlesW95** [comment]
Ah okay I see. That was very helpful - thank you!!
